//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTransferLines.Dal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Acente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acente()
        {
            this.Surucu = new HashSet<Surucu>();
            this.Transfer = new HashSet<Transfer>();
        }
    
        public int AcenteID { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Nullable<int> SehirID { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string AcenteAdi { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string FirmaUnvan { get; set; }
        public string Yetkili { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> Sozlesme { get; set; }
        public Nullable<System.DateTime> SozlesmeOnayTarih { get; set; }
        public Nullable<System.DateTime> SonLogin { get; set; }
        public string Iban { get; set; }
        public string VergiDaire { get; set; }
        public string VergiDaireNo { get; set; }
        public string YetkiliTel { get; set; }
        public string Kredi { get; set; }
        public string FaturaAdres { get; set; }
        public string Notlar { get; set; }
        public string Sifre { get; set; }
        public string YetkiliEmail { get; set; }
    
        public virtual Sehir Sehir { get; set; }
        public virtual Ulke Ulke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surucu> Surucu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer { get; set; }
    }
}
