//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTransferLines.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int transferID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<int> aracID { get; set; }
        public Nullable<int> acentaID { get; set; }
        public Nullable<int> surucuID { get; set; }
        public Nullable<int> dilID { get; set; }
        public string nereden { get; set; }
        public string nereye { get; set; }
        public string fromName { get; set; }
        public string toName { get; set; }
        public Nullable<int> kisiSayisi { get; set; }
        public Nullable<int> bagajSayisi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.TimeSpan> saat { get; set; }
        public Nullable<int> km { get; set; }
        public string sureSaat { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<decimal> ekstrasızFiyat { get; set; }
        public string doviz { get; set; }
        public Nullable<int> UlkeID { get; set; }
    
        public virtual Acente Acente { get; set; }
        public virtual Arac Arac { get; set; }
        public virtual Dil Dil { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Surucu Surucu { get; set; }
        public virtual Ulke Ulke { get; set; }
    }
}
